---
title: "DataAnalysis"
author: "Sarah I. Murphy"
date: "2/6/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set-up environment
```{r}
#load packages
library(readr)
library(tidyverse)
library(splitstackshape)
library(ggplot2)

#load data
load("~/Documents/Projects_Papers/2020_Projects/2020_MilkMC/MC-2020/Sarah_UpstateBuffalo_BactofugeSimulations/Baseline_Buffalo_NoBactofuge_AverageSpoilageType_LaplaceTemp_MCsim_result_df.RData")
load("~/Documents/Projects_Papers/2020_Projects/2020_MilkMC/MC-2020/Sarah_UpstateBuffalo_BactofugeSimulations/Baseline_Buffalo_MoraruBactofuge_AverageSpoilageType_LaplaceTemp_MCsim_result_df.RData")
load("~/Documents/Projects_Papers/2020_Projects/2020_MilkMC/MC-2020/Sarah_UpstateBuffalo_BactofugeSimulations/Baseline_Buffalo_TetraPakBactofuge_AverageSpoilageType_LaplaceTemp_MCsim_result_df.RData")
load("~/Documents/Projects_Papers/2020_Projects/2020_MilkMC/MC-2020/Sarah_UpstateBuffalo_BactofugeSimulations/Buffalo_NoBactofuge_WorstPPCVSL434_LaplaceTemp_MCsim_result_df.RData")
load("~/Documents/Projects_Papers/2020_Projects/2020_MilkMC/MC-2020/Sarah_UpstateBuffalo_BactofugeSimulations/Buffalo_MoraruBactofuge_WorstPPCVSL434_LaplaceTemp_MCsim_result_df.RData")
load("~/Documents/Projects_Papers/2020_Projects/2020_MilkMC/MC-2020/Sarah_UpstateBuffalo_BactofugeSimulations/Buffalo_TetraPakBactofuge_WorstPPCVSL434_LaplaceTemp_MCsim_result_df.RData")
load("~/Documents/Projects_Papers/2020_Projects/2020_MilkMC/MC-2020/Sarah_UpstateBuffalo_BactofugeSimulations/Buffalo_NoBactofuge_BestPPCVSL436_LaplaceTemp_MCsim_result_df.RData")
load("~/Documents/Projects_Papers/2020_Projects/2020_MilkMC/MC-2020/Sarah_UpstateBuffalo_BactofugeSimulations/Buffalo_MoraruBactofuge_BestPPCVSL436_LaplaceTemp_MCsim_result_df.RData")
load("~/Documents/Projects_Papers/2020_Projects/2020_MilkMC/MC-2020/Sarah_UpstateBuffalo_BactofugeSimulations/Buffalo_TetraPakBactofuge_BestPPCVSL436_LaplaceTemp_MCsim_result_df.RData")
load("~/Documents/Projects_Papers/2020_Projects/2020_MilkMC/MC-2020/Sarah_UpstateBuffalo_BactofugeSimulations/Baseline_Buffalo_NoBactofuge_AverageSpoilageType_ConstantTemp_MCsim_result_df.RData")
load("~/Documents/Projects_Papers/2020_Projects/2020_MilkMC/MC-2020/Sarah_UpstateBuffalo_BactofugeSimulations/Baseline_Buffalo_MoraruBactofuge_AverageSpoilageType_ConstantTemp_MCsim_result_df.RData")
load("~/Documents/Projects_Papers/2020_Projects/2020_MilkMC/MC-2020/Sarah_UpstateBuffalo_BactofugeSimulations/Baseline_Buffalo_TetraPakBactofuge_AverageSpoilageType_ConstantTemp_MCsim_result_df.RData")
load("~/Documents/Projects_Papers/2020_Projects/2020_MilkMC/MC-2020/Sarah_UpstateBuffalo_BactofugeSimulations/Buffalo_NoBactofuge_WorstPPCVSL434_ConstantTemp_MCsim_result_df.RData")
load("~/Documents/Projects_Papers/2020_Projects/2020_MilkMC/MC-2020/Sarah_UpstateBuffalo_BactofugeSimulations/Buffalo_MoraruBactofuge_WorstPPCVSL434_ConstantTemp_MCsim_result_df.RData")
load("~/Documents/Projects_Papers/2020_Projects/2020_MilkMC/MC-2020/Sarah_UpstateBuffalo_BactofugeSimulations/Buffalo_TetraPakBactofuge_WorstPPCVSL434_ConstantTemp_MCsim_result_df.RData")
load("~/Documents/Projects_Papers/2020_Projects/2020_MilkMC/MC-2020/Sarah_UpstateBuffalo_BactofugeSimulations/Buffalo_NoBactofuge_BestPPCVSL436_ConstantTemp_MCsim_result_df.RData")
load("~/Documents/Projects_Papers/2020_Projects/2020_MilkMC/MC-2020/Sarah_UpstateBuffalo_BactofugeSimulations/Buffalo_MoraruBactofuge_BestPPCVSL436_ConstantTemp_MCsim_result_df.RData")
load("~/Documents/Projects_Papers/2020_Projects/2020_MilkMC/MC-2020/Sarah_UpstateBuffalo_BactofugeSimulations/Buffalo_TetraPakBactofuge_BestPPCVSL436_ConstantTemp_MCsim_result_df.RData")
```

* Merge the data
```{r}
# colnames(data_NB_MeanSpoilType_CT)[6] <- "NB_MeanSpoilType_CT"
# colnames(data_NB_MeanSpoilType_LT)[6] <- "NB_MeanSpoilType_LT"
# colnames(data_NB_BestPPCVSL436_CT)[6] <- "NB_BestPPCVSL436_CT"
# colnames(data_NB_BestPPCVSL436_LT)[6] <- "NB_BestPPCVSL436_LT"
# colnames(data_NB_WorstPPCVSL434_CT)[6] <- "NB_WorstPPCVSL434_CT"
# colnames(data_NB_WorstPPCVSL434_LT)[6] <- "NB_WorstPPCVSL434_LT"
# colnames(data_MB_MeanSpoilType_CT)[6] <- "MB_MeanSpoilType_CT"
# colnames(data_MB_MeanSpoilType_LT)[6] <- "MB_MeanSpoilType_LT"
# colnames(data_MB_BestPPCVSL436_CT)[6] <- "MB_BestPPCVSL436_CT"
# colnames(data_MB_BestPPCVSL436_LT)[6] <- "MB_BestPPCVSL436_LT"
# colnames(data_MB_WorstPPCVSL434_CT)[6] <- "MB_WorstPPCVSL434_CT"
# colnames(data_MB_WorstPPCVSL434_LT)[6] <- "MB_WorstPPCVSL434_LT"
# colnames(data_TB_MeanSpoilType_CT)[6] <- "TB_MeanSpoilType_CT"
# colnames(data_TB_MeanSpoilType_LT)[6] <- "TB_MeanSpoilType_LT"
# colnames(data_TB_BestPPCVSL436_CT)[6] <- "TB_BestPPCVSL436_CT"
# colnames(data_TB_BestPPCVSL436_LT)[6] <- "TB_BestPPCVSL436_LT"
# colnames(data_TB_WorstPPCVSL434_CT)[6] <- "TB_WorstPPCVSL434_CT"
# colnames(data_TB_WorstPPCVSL434_LT)[6] <- "TB_WorstPPCVSL434_LT"
# 
# colnames(data_NB_MeanSpoilType_CT)[4] <- "SpT_NB_MeanSpoilType_CT"
# colnames(data_NB_MeanSpoilType_LT)[4] <- "SpT_NB_MeanSpoilType_LT"
# colnames(data_NB_BestPPCVSL436_CT)[4] <- "SpT_NB_BestPPCVSL436_CT"
# colnames(data_NB_BestPPCVSL436_LT)[4] <- "SpT_NB_BestPPCVSL436_LT"
# colnames(data_NB_WorstPPCVSL434_CT)[4] <- "SpT_NB_WorstPPCVSL434_CT"
# colnames(data_NB_WorstPPCVSL434_LT)[4] <- "SpT_NB_WorstPPCVSL434_LT"
# colnames(data_MB_MeanSpoilType_CT)[4] <- "SpT_MB_MeanSpoilType_CT"
# colnames(data_MB_MeanSpoilType_LT)[4] <- "SpT_MB_MeanSpoilType_LT"
# colnames(data_MB_BestPPCVSL436_CT)[4] <- "SpT_MB_BestPPCVSL436_CT"
# colnames(data_MB_BestPPCVSL436_LT)[4] <- "SpT_MB_BestPPCVSL436_LT"
# colnames(data_MB_WorstPPCVSL434_CT)[4] <- "SpT_MB_WorstPPCVSL434_CT"
# colnames(data_MB_WorstPPCVSL434_LT)[4] <- "SpT_MB_WorstPPCVSL434_LT"
# colnames(data_TB_MeanSpoilType_CT)[4] <- "SpT_TB_MeanSpoilType_CT"
# colnames(data_TB_MeanSpoilType_LT)[4] <- "SpT_TB_MeanSpoilType_LT"
# colnames(data_TB_BestPPCVSL436_CT)[4] <- "SpT_TB_BestPPCVSL436_CT"
# colnames(data_TB_BestPPCVSL436_LT)[4] <- "SpT_TB_BestPPCVSL436_LT"
# colnames(data_TB_WorstPPCVSL434_CT)[4] <- "SpT_TB_WorstPPCVSL434_CT"
# colnames(data_TB_WorstPPCVSL434_LT)[4] <- "SpT_TB_WorstPPCVSL434_LT"
# 
# df1 <- data_NB_MeanSpoilType_CT[c(1:2,4:6)]
# df2 <- data_NB_MeanSpoilType_LT[c(1:2,4:6)]
# df3 <- data_MB_MeanSpoilType_CT[c(1:2,4:6)]
# df4 <- data_MB_MeanSpoilType_LT[c(1:2,4:6)]
# df5 <- data_TB_MeanSpoilType_CT[c(1:2,4:6)]
# df6 <- data_TB_MeanSpoilType_LT[c(1:2,4:6)]
# df7 <- data_NB_BestPPCVSL436_CT[c(1:2,4:6)]
# df8 <- data_NB_BestPPCVSL436_LT[c(1:2,4:6)]
# df9 <- data_MB_BestPPCVSL436_CT[c(1:2,4:6)]
# df10 <- data_MB_BestPPCVSL436_LT[c(1:2,4:6)]
# df11 <- data_TB_BestPPCVSL436_CT[c(1:2,4:6)]
# df12 <- data_TB_BestPPCVSL436_LT[c(1:2,4:6)]
# df13 <- data_NB_WorstPPCVSL434_CT[c(1:2,4:6)]
# df14 <- data_NB_WorstPPCVSL434_LT[c(1:2,4:6)]
# df15 <- data_MB_WorstPPCVSL434_CT[c(1:2,4:6)]
# df16 <- data_MB_WorstPPCVSL434_LT[c(1:2,4:6)]
# df17 <- data_TB_WorstPPCVSL434_CT[c(1:2,4:6)]
# df18 <- data_TB_WorstPPCVSL434_LT[c(1:2,4:6)]

# df <- merge(df1,df2)
# df <- merge(df,df3)
# df <- merge(df,df4)
# df <- merge(df,df5)
# df <- merge(df,df6)
# df <- merge(df,df7)
# df <- merge(df,df8)
# df <- merge(df,df9)
# df <- merge(df,df10)
# df <- merge(df,df11)
# df <- merge(df,df12)
# df <- merge(df,df13)
# df <- merge(df,df14)
# df <- merge(df,df15)
# df <- merge(df,df16)
# df <- merge(df,df17)
# df <- merge(df,df18)

data_NB_MeanSpoilType_CT$scenario <- "NB_MeanSpoilType_CT"
data_NB_MeanSpoilType_LT$scenario <- "NB_MeanSpoilType_LT"
data_MB_MeanSpoilType_CT$scenario <- "MB_MeanSpoilType_CT"
data_MB_MeanSpoilType_LT$scenario <- "MB_MeanSpoilType_LT"
data_TB_MeanSpoilType_CT$scenario <- "TB_MeanSpoilType_CT"
data_TB_MeanSpoilType_LT$scenario <- "TB_MeanSpoilType_LT"
data_NB_BestPPCVSL436_CT$scenario <- "NB_BestPPCVSL436_CT"
data_NB_BestPPCVSL436_LT$scenario <- "NB_BestPPCVSL436_LT"
data_MB_BestPPCVSL436_CT$scenario <- "MB_BestPPCVSL436_CT"
data_MB_BestPPCVSL436_LT$scenario <- "MB_BestPPCVSL436_LT"
data_TB_BestPPCVSL436_CT$scenario <- "TB_BestPPCVSL436_CT"
data_TB_BestPPCVSL436_LT$scenario <- "TB_BestPPCVSL436_LT"
data_NB_WorstPPCVSL434_CT$scenario <- "NB_WorstPPCVSL434_CT"
data_NB_WorstPPCVSL434_LT$scenario <- "NB_WorstPPCVSL434_LT"
data_MB_WorstPPCVSL434_CT$scenario <- "MB_WorstPPCVSL434_CT"
data_MB_WorstPPCVSL434_LT$scenario <- "MB_WorstPPCVSL434_LT"
data_TB_WorstPPCVSL434_CT$scenario <- "TB_WorstPPCVSL434_CT"
data_TB_WorstPPCVSL434_LT$scenario <- "TB_WorstPPCVSL434_LT"

df1 <- data_NB_MeanSpoilType_CT[c(1:2,4:6,19)]
df2 <- data_NB_MeanSpoilType_LT[c(1:2,4:6,19)]
df3 <- data_MB_MeanSpoilType_CT[c(1:2,4:6,19)]
df4 <- data_MB_MeanSpoilType_LT[c(1:2,4:6,19)]
df5 <- data_TB_MeanSpoilType_CT[c(1:2,4:6,19)]
df6 <- data_TB_MeanSpoilType_LT[c(1:2,4:6,19)]
df7 <- data_NB_BestPPCVSL436_CT[c(1:2,4:6,19)]
df8 <- data_NB_BestPPCVSL436_LT[c(1:2,4:6,19)]
df9 <- data_MB_BestPPCVSL436_CT[c(1:2,4:6,19)]
df10 <- data_MB_BestPPCVSL436_LT[c(1:2,4:6,19)]
df11 <- data_TB_BestPPCVSL436_CT[c(1:2,4:6,19)]
df12 <- data_TB_BestPPCVSL436_LT[c(1:2,4:6,19)]
df13 <- data_NB_WorstPPCVSL434_CT[c(1:2,4:6,19)]
df14 <- data_NB_WorstPPCVSL434_LT[c(1:2,4:6,19)]
df15 <- data_MB_WorstPPCVSL434_CT[c(1:2,4:6,19)]
df16 <- data_MB_WorstPPCVSL434_LT[c(1:2,4:6,19)]
df17 <- data_TB_WorstPPCVSL434_CT[c(1:2,4:6,19)]
df18 <- data_TB_WorstPPCVSL434_LT[c(1:2,4:6,19)]

df <- rbind(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,df18)

rm(list=setdiff(ls(), c("df")))
```

## Data Analysis   ----
```{r}
# change numeric vars to factors
df$lot_id<- as.factor(df$lot_id)
df$day<- as.factor(df$day)

# separate scenario
df <- separate(data=df,scenario,c("Bactofuge","PPCFreq","Temp"),remove = FALSE)
```

```{r}
#Calculate the mean count by day
df_percent_byScenario_byDay<- df %>%
  group_by(scenario,Bactofuge,PPCFreq,Temp,day) %>%
  summarize(n_total = n(),
            n_exceed1000=sum(count >3),
            per_exceed1000=n_exceed1000/n_total*100,
            n_exceed5mill=sum(count >6.69897),
            per_exceed5mill=n_exceed5mill/n_total*100,
            n_exceed1mill=sum(count > 6),
            per_exceed1mill=n_exceed1mill/n_total*100,
            n_exceed10mill=sum(count > 7),
            per_exceed10mill=n_exceed10mill/n_total*100,
            n_exceed20mill=sum(count > 7.3),
            per_exceed20mill=n_exceed20mill/n_total*100,
            n_exceed30mill=sum(count > 7.47),
            per_exceed30mill=n_exceed30mill/n_total*100,
            n_exceed40mill=sum(count > 7.6),
            per_exceed40mill=n_exceed40mill/n_total*100,
            n_exceed20000=sum(count > 4.3),
            per_exceed20000=n_exceed20000/n_total*100) 
df_percent_byScenario_byDay <- df_percent_byScenario_byDay[c(1:5,8,10,12,14,16,18,20,22,7,9,11,13,15,17,19,21,6)]

#Calculate the mean count by day
df_mean_byScenario_byDay <- df %>%
  group_by(scenario,day) %>%
  summarize(mean = mean(count), sd = sd(count))

#Calculate the mean above 20,000 CFU
df_mean_byScenario_byDaybyLot <- df %>%
  group_by(scenario,day,lot_id) %>%
  summarize(mean = mean(count), sd = sd(count))

# test <- df %>% # this shows us that we need more simulations
#   group_by(scenario,Bactofuge,PPCFreq,Temp,lot_id,day) %>%
#   summarize(n_total = n(),
#             n_exceed1000=sum(count >3),
#             per_exceed1000=n_exceed1000/n_total*100) %>%
#   ungroup()%>%
#   group_by(scenario,Bactofuge,PPCFreq,Temp,day)%>%
#   summarize(ntot=n(),
#             mean_perexceed1000=mean(per_exceed1000),
#             sd_perexceed1000=sd(per_exceed1000))

#Calculate the mean count by day by spoilage_type
df_mean_byScenario_byDay_bySpoilageType <- df %>%
  group_by(spoilage_type,scenario,day) %>%
  summarize(mean = mean(count), sd = sd(count))

# find the day in shelf life where the mean of 

# Save df as .csv
write.csv(df_mean_byScenario_byDay, "df_mean_byScenario_byDay_Buffalo.csv")
write.csv(df_mean_byScenario_byDay_bySpoilageType, "df_mean_byScenario_byDay_bySpoilageType_Buffalo.csv")
write.csv(df_percent_byScenario_byDay, "df_percent_byScenario_byDay_Buffalo.csv")
```

```{r}
ggplot(data=df, aes(x=day,y=count, col=spoilage_type))+
  geom_violin()+
  scale_x_discrete(breaks = seq(1, 35, 1), labels=seq(1, 35, 1)) +
  scale_y_continuous(breaks = seq(-6, 12, 2),limits = c(-6,12))+
  labs(y = "Milk aerobic plate count (log CFU or MPN/mL)", x = "Day" )+
  facet_grid(Temp~Bactofuge+PPCFreq)

ggplot(data=df, aes(x=day,y=count, col=spoilage_type))+
  geom_jitter(shape=3)+
  scale_x_discrete(breaks = seq(1, 35, 1), labels=seq(1, 35, 1)) +
  scale_y_continuous(breaks = seq(-6, 12, 2),limits = c(-6,12))+
  labs(y = "Milk SPC (log CFU or MPN/mL)", x = "Day")+
  facet_grid(Temp~Bactofuge+PPCFreq)
```



```{r}
#Plot
# pdf(file='plot_mu_low_worstcase_summary.pdf')
# fig1 <- ggplot() + 
#   geom_bar(aes(y = spoiled_by_day$spoiled, x = spoiled_by_day$days), data = spoiled_by_day, 
#                                stat = "identity", color = "black", position = "dodge") +
#   geom_text(data = spoiled_by_day, 
#                                aes(x = spoiled_by_day$days, y = spoiled_by_day$spoiled, label = round(spoiled_by_day$spoiled, 2)), 
#                                position=position_dodge(width = 1), 
#                                vjust=-0.25, size = 4)+
#   labs(y = "Percent of samples > 4.3 logMPN/mL", x = "Day" )+
#   scale_x_discrete(breaks = seq(1, 24, 1), labels=seq(1, 24, 1)) +
#   scale_y_continuous(limits = c(0, 100), expand = c(0, 0))+
#   ggtitle("Overall")
# fig1
```

```{r}
#Plot
spore_fig1 <- ggplot() + 
  geom_bar(aes(y = spore_spoiled_by_day$spore_spoiled, x = spore_spoiled_by_day$spore_days), data = spore_spoiled_by_day, stat = "identity", color = "black", position = "dodge") +
  geom_text(data = spore_spoiled_by_day, 
                               aes(x = spore_spoiled_by_day$spore_days, y = spore_spoiled_by_day$spore_spoiled, label = round(spore_spoiled_by_day$spore_spoiled, 2)), 
                               position=position_dodge(width = 1), 
                               vjust=-0.25, size = 4)+
  labs(y = "Percent of samples > 4.3 log10MPN/mL", x = "Day" )+
  scale_x_discrete(breaks = seq(1, 24, 1), labels=seq(1, 24, 1)) +
  scale_y_continuous(limits = c(0, 100), expand = c(0, 0))+
  ggtitle("Samples that spoiled due to spores")
spore_fig1

ppc_fig1 <- ggplot() + 
  geom_bar(aes(y = ppc_spoiled_by_day$ppc_spoiled, x = ppc_spoiled_by_day$ppc_days), data = ppc_spoiled_by_day, 
                               stat = "identity", color = "black", position = "dodge") +
  geom_text(data = ppc_spoiled_by_day, 
                               aes(x = ppc_spoiled_by_day$ppc_days, y = ppc_spoiled_by_day$ppc_spoiled, label = round(ppc_spoiled_by_day$ppc_spoiled, 2)), 
                               position=position_dodge(width = 1), 
                               vjust=-0.25, size = 4)+
  labs(y = "Percent of samples > 4.3 log10MPN/mL", x = "Day" )+
  scale_x_discrete(breaks = seq(1, 24, 1), labels=seq(1, 24, 1)) +
  scale_y_continuous(limits = c(0, 100), expand = c(0, 0))+
  ggtitle("Samples that spoiled due to PPC")
ppc_fig1
```

```{r}
##
#Make df of data by day
d0<-data[c(1:4,9)]
d0<-unique(d0)
d1<- data[data$day=="1",] 
d2<- data[data$day=="2",] 
d3<- data[data$day=="3",] 
d4<- data[data$day=="4",] 
d5<- data[data$day=="5",] 
d6<- data[data$day=="6",] 
d7<- data[data$day=="7",] 
d8<- data[data$day=="8",] 
d9<- data[data$day=="9",] 
d10<- data[data$day=="10",]
d11<- data[data$day=="11",] 
d12<- data[data$day=="12",] 
d13<- data[data$day=="13",] 
d14<- data[data$day=="14",] 
d15<- data[data$day=="15",]
d16<- data[data$day=="16",]
d17<- data[data$day=="17",]
d18<- data[data$day=="18",]
d19<- data[data$day=="19",]
d20<- data[data$day=="20",]
d21<- data[data$day=="21",]
d22<- data[data$day=="22",]
d23<- data[data$day=="23",]
d24<- data[data$day=="24",]

```

```{r}
#plot each day simulated histogram;

# pdf(file='plot_initialmicro_low_bestcase.pdf')
hist(d0$logCount_init, main="Histogram of simulated milk spore count over shelf-life\n Day = 0",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d1$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 1",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d2$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 2",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d3$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 3",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d4$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 4",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d5$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 5",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d6$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 6",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d7$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 7",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d8$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 8",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d9$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 9",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d10$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 10",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d11$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 11",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d12$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 12",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d13$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 13",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d14$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 14",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d15$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 15",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d16$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 16",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d17$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 17",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d18$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 18",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d19$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 19",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d20$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 20",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d21$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 21",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d22$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 22",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d23$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 23",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")
hist(d24$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 24",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-4,8), ylim=c(0,500),breaks=20, col="gray")

# dev.off()
```

```{r}
ggplot(d0, aes(logCount_init, fill = spoilage_type)) +
  geom_histogram(bins=20)
ggplot(data, aes(count, fill = spoilage_type)) +
  geom_histogram()+
  facet_wrap(~day)
```

* make an animation of simulation results
```{r}
library(gganimate)
df2 <- df
df2 <- df2 %>%
  filter(Temp=="CT") 
  # filter(PPCFreq=="MeanSpoilType")
df2$day <- as.integer(df2$day)
p <- ggplot(df2,
  aes(x = count, fill = spoilage_type)) +
  geom_histogram(show.legend = TRUE, alpha = 0.7,bins=20) +
  scale_y_continuous(breaks = seq(0,500,50))+
  scale_x_continuous(breaks = seq(-4, 10, 2)) +
  facet_grid(PPCFreq~Bactofuge)+
  # facet_grid(Temp~Bactofuge+PPCFreq)+
  transition_time(day) +
  labs(title = "Day: {frame_time}",x="Milk bacteria count (log10 MPN or CFU/mL)") +
  view_follow(fixed_y = TRUE)
p
```


```{r}
#plot histogram with both the simulated and fake actual count data
d0_mean <- d0 %>%
  group_by(LOT) %>%
  summarise(mean = mean(logCFU_init), sd = sd(logCFU_init))

plot(density(d0$logCFU_init), main="Day 0 - simulated initial count data vs input initial count data", 
     xlab="LOG CFU/g", xlim=c(0,10), ylim=c(0,4))
lines(density(initialcount_import$log10_mean_count), col="blue")
legend('topright',  legend = c("simulated", "actual"), 
       lty=1, col=c('black', 'blue'), bty='n', cex=.75)
```


```{r}
# data_d10_sim <- data[data$day=="10",]
# data_d10_sim <- data_d10_sim %>%
#   filter(spoilage_type == "ppc")
# freq_spoilageType <- freq_spoilageType %>%
#   filter(spoilagetype == "ppc")
# freq_spoilageType$log10SPC_D10<- log10(freq_spoilageType$SPC_D10)
# ks.test(data_d10_sim$count, freq_spoilageType$log10SPC_D10, alternative = c("two.sided"), exact = NULL)
# p_ecdf_d10_sim <- ecdf(data_d10_sim$count)
# p_ecdf_d10_actual <- ecdf(freq_spoilageType$log10SPC_D10)
# plot(p_ecdf_d10_sim, verticals = TRUE, do.points=FALSE)
# plot(p_ecdf_d10_actual, verticals = TRUE, do.points=FALSE, add=TRUE, col="blue")
# 
# data_d10_sim <- data[data$day=="10",]
# freq_spoilageType$log10SPC_D10<- log10(freq_spoilageType$SPC_D10)
# ks.test(data_d10_sim$count, freq_spoilageType$log10SPC_D10, alternative = c("two.sided"), exact = NULL)
# p_ecdf_d10_sim <- ecdf(data_d10_sim$count)
# p_ecdf_d10_actual <- ecdf(freq_spoilageType$log10SPC_D10)
# plot(p_ecdf_d10_sim, verticals = TRUE, do.points=FALSE)
# plot(p_ecdf_d10_actual, verticals = TRUE, do.points=FALSE, add=TRUE, col="blue")
# 
# data_d14_sim <- data[data$day=="14",]
# data_d14_sim <- data_d14_sim %>%
#   filter(spoilage_type == "ppc")
# freq_spoilageType$log10SPC_D14<- log10(freq_spoilageType$SPC_D14)
# ks.test(data_d14_sim$count, freq_spoilageType$log10SPC_D14, alternative = c("two.sided"), exact = NULL)
# p_ecdf_d14_sim <- ecdf(data_d14_sim$count)
# p_ecdf_d14_actual <- ecdf(freq_spoilageType$log10SPC_D14)
# plot(p_ecdf_d14_sim, verticals = TRUE, do.points=FALSE)
# plot(p_ecdf_d14_actual, verticals = TRUE, do.points=FALSE, add=TRUE, col="blue")
# 
# data_d17_sim <- data[data$day=="17",]
# data_d17_sim <- data_d17_sim %>%
#   filter(spoilage_type == "ppc")
# freq_spoilageType$log10SPC_D17<- log10(freq_spoilageType$SPC_D17)
# ks.test(data_d17_sim$count, freq_spoilageType$log10SPC_D17, alternative = c("two.sided"), exact = NULL)
# p_ecdf_d17_sim <- plot(ecdf(data_d17_sim$count))
# p_ecdf_d17_actual <- ecdf(freq_spoilageType$log10SPC_D17)

```

