---
title: "DataAnalysis"
author: "Sarah I. Murphy"
date: "2/6/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set-up environment
```{r}
#load packages
library(readr)
library(dplyr)
library(splitstackshape)
library(ggplot2)

#load data
load("MCsim_result_df.RData")
```

## Data Analysis   ----
```{r}
data$bulk_tank<- as.factor(data$bulk_tank)
data$day<- as.factor(data$day)

#Calculate the mean count by day
data %>%
  group_by(day) %>%
  summarise(mean = mean(count), sd = sd(count))-> mean_by_day
mean_by_day
```

```{r}
ggplot(data=data, aes(x=day,y=count))+
  geom_boxplot()+
  scale_y_continuous(limits = c(-5, 15), breaks = seq(-5, 15, by = 1))+
  labs(y = "Milk spore count (log MPN/mL)", x = "Day" )

ggplot(data=data, aes(x=day,y=count))+
  geom_violin()+
  scale_y_continuous(limits = c(-5, 15), breaks = seq(-5, 15, by = 1))+
  labs(y = "Milk spore count (log MPN/mL)", x = "Day" )

```



```{r}
#what percent of samples spoiled for each day in shelf life
days <- seq(1, 24, 1)
spoiled <- vector(mode = "logical", length(days))
spoiled_by_day <- data.frame(days, spoiled)

for (d in days) {
  numerator <-   length(which(subset(data, data$day == d)$count>4.3))
  denominator <- length(subset(data, data$day == d)$count)
  
  spoiled_by_day[spoiled_by_day$days==d,]$spoiled <- numerator / denominator * 100
}

spoiled_by_day$days <- factor(spoiled_by_day$days)

#Plot
# pdf(file='plot_mu_low_worstcase_summary.pdf')
fig1 <- ggplot() + 
  geom_bar(aes(y = spoiled_by_day$spoiled, x = spoiled_by_day$days), data = spoiled_by_day, 
                               stat = "identity", color = "black", position = "dodge") +
  geom_text(data = spoiled_by_day, 
                               aes(x = spoiled_by_day$days, y = spoiled_by_day$spoiled, label = round(spoiled_by_day$spoiled, 2)), 
                               position=position_dodge(width = 1), 
                               vjust=-0.25, size = 4)+
  labs(y = "Percent of samples > 4.3 logMPN/mL", x = "Day" )+
  scale_x_discrete(breaks = seq(1, 24, 1), labels=seq(1, 24, 1)) +
  scale_y_continuous(limits = c(0, 100), expand = c(0, 0))
fig1
```
```{r}
#What percent of samples spoiled by day 14?
length(which(subset(data, data$day == 14)$count>4.3))/length(subset(data, data$day == 14)$count)

#What percent of samples spoiled by day 21?
length(which(subset(data, data$day == 21)$count>4.3))/length(subset(data, data$day == 21)$count)

#What percent of samples spoiled by day 24?
length(which(subset(data, data$day == 24)$count>4.3))/length(subset(data, data$day == 24)$count)

```

```{r}
##
#Make df of data by day
# d0<-data[c(1:3,6)]
# d0<-unique(d0)
d1<- data[data$day=="1",] 
d2<- data[data$day=="2",] 
d3<- data[data$day=="3",] 
d4<- data[data$day=="4",] 
d5<- data[data$day=="5",] 
d6<- data[data$day=="6",] 
d7<- data[data$day=="7",] 
d8<- data[data$day=="8",] 
d9<- data[data$day=="9",] 
d10<- data[data$day=="10",]
d11<- data[data$day=="11",] 
d12<- data[data$day=="12",] 
d13<- data[data$day=="13",] 
d14<- data[data$day=="14",] 
d15<- data[data$day=="15",]
d16<- data[data$day=="16",]
d17<- data[data$day=="17",]
d18<- data[data$day=="18",]
d19<- data[data$day=="19",]
d20<- data[data$day=="20",]
d21<- data[data$day=="21",]
d22<- data[data$day=="22",]
d23<- data[data$day=="23",]
d24<- data[data$day=="24",]

```

```{r}
#plot each day simulated histogram;

# pdf(file='plot_initialmicro_low_bestcase.pdf')
hist(d1$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 1",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d2$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 2",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d3$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 3",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d4$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 4",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d5$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 5",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d6$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 6",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d7$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 7",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d8$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 8",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d9$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 9",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d10$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 10",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d11$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 11",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d12$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 12",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d13$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 13",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d14$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 14",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d15$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 15",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d16$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 16",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d17$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 17",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d18$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 18",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d19$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 19",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d20$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 20",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d21$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 21",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d22$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 22",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d23$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 23",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")
hist(d24$count, main="Histogram of simulated milk spore count over shelf-life\n Day = 24",  xlab=expression('Log'['10']*'MPN/mL'), xlim=c(-5,15), ylim=c(0,500),breaks=20, col="gray")

# dev.off()
```