---
title: "MCsim_020620"
author: "Sarah I. Murphy"
date: "2/6/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set-up environment
* load packages
* load functions
* load data
* set seed for reproducibilty
```{r}
## load packages
library(readr)

## load functions
source("UtilityFunctions.R")

## load data

#frequency data
frequency_file <- "Frequency.csv"
freq_import <- read.csv(frequency_file, stringsAsFactors = FALSE, header = TRUE)

#growth parameter data
growth_file <- "GrowthParameters.csv" #make sure this contains growth parameters & growth model name
growth_import <-read.csv(growth_file, stringsAsFactors = FALSE)

#initial count logMPN data
init_file <- "InitialCountsMPN.csv"
initialcount_import <- read.csv(init_file, stringsAsFactors = FALSE)

#temperature data for each stage
temp_by_stage <- read.csv(temp_stages_file, stringsAsFactors = F, comment.char = "#")

## set seed
set.seed(1)
```

# Set-up dataframe
```{r}
##Set important parameters for running the simulation:

# (1) n_sim
# Definition: Number of simulations to run (also referred to as the number of bulk tanks in earlier code; i.e., 1 simulation unit = 1 bulk tank of milk)
n_sim <-100    #1000 is for testing and exploring, experiments require at least 10k

#(2) n_units 
# Definition: Number of units per lot (currently, half gallon units) 
n_units <-10

# (3) start_day 
# Definition: First time point (in days) in unit's shelf life to simulate
start_day <- 1 

# (4) end_day 
# Definition: Last time point (in days) in unit's shelf life to simulate
end_day <- 24 
n_day <- 24 # seems like this is the end_day, but keeping code below for now in case my interpretation is wrong

## Prep vectors using defined values above
# (1) bulk_tank
#Make a vector for "bulk tank" by repeating sequence of 1:n_sim for length of n_units * n_day
bulk_tank <- rep(seq(1, n_sim), each = n_units * n_day)

# (2) milk_unit
#Make a vector for "milk_unit" by repeating the sequence of 1:n_units by n_day * n_sim
milk_unit <- rep(seq(1, n_units), times = n_day * n_sim) 

# (3) AT
# Make an empty vector for "AT" with the length of n_sim * n_units * n_day
AT <- vector(mode="logical", n_sim * n_units * n_day) 

# (4) day
#Make a vector repeating days in shelf life that are simulated for each simulation run (i.e., each bulk tank) 
day <- rep(rep(seq(start_day, start_day+n_day-1), each = n_units), times = n_sim) 

# (5) count
#Make an empty vector for "count" with the length of n_sim * n_units * n_day
count <- vector(mode = "logical", n_sim * n_units * n_day) 

## Prep dataframe using vectors above (each vector becomes a column)
data <- data.frame(bulk_tank, milk_unit, AT, day, count)
```

