---
title: "Texas_AT_Assignment"
author: "Tim L"
date: "11/19/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Based on Code from ATbyTree_3.8.17.R - Date: Feb 7, 2020

#Load packages
```{r}
library(stringr)
library(ape)
library(usedist)
library(dplyr)
library(tidyr)
```

```{r}
#read in raw file with AT counts
ATcompare <- read.csv("~/Github/Lab/MC-2020/Tim_ESL/SporeModel_092120/ATFrequency_Excelv.csv", stringsAsFactors = FALSE)

#create df to replicate AT by count
ComTXFreq <- ATcompare %>% 
 drop_na(AT)%>% 
  tibble(x = AT,n = n_Txcom)

#remove all columns except AT
TXcombined_ATfreq <- uncount(ComTXFreq, ComTXFreq$n) %>% 
  select(AT) 
  
#rename AT to realat
TXcombined_ATfreq <- rename(TXcombined_ATfreq, RealAT = AT)
```

```{r}
#Growthparameters.csv Sep 24, 2020 in ...Tim_ESL > SporeModel_092120 > InputFiles
growth_import <- read.csv("~/Github/Lab/MC-2020/Tim_ESL/SporeModel_092120/InputFiles/GrowthParameters.csv", stringsAsFactors = FALSE)

growth_import <- na.omit(growth_import)

#ColdgrowATFreq_CrossSect.csv from Feb 7, 2020
AT_import <- TXcombined_ATfreq

AT_import <- na.omit(AT_import)
```

```{r}
All_ATs <- AT_import[,1]
closest.allele<-c()
mytree<-read.tree("~/Github/Lab/MC-2020/Tim_ESL/SporeModel_092120/RAxML_bipartitions.rpoB_RAML_tree")
pw.dist<-cophenetic.phylo(mytree)
good.alleles<-str_pad(growth_import$rpoBAT,4,pad="0")
allele_samp <- All_ATs
for (a in 1:length(allele_samp)){
            newsamp<-str_pad(allele_samp[a],4,pad="0")
  if (newsamp%in%good.alleles){
    splitat.best<-substr(newsamp,regexpr("[^0]",newsamp),nchar(newsamp))
    closest.allele<-append(closest.allele,splitat.best)
  }
  else{
    at.query<-colnames(pw.dist)[which(grepl(paste("AT",newsamp,sep=""),colnames(pw.dist))==TRUE)]
    mindist<-Inf
    for (g in 1:length(good.alleles)){
      gquery<-colnames(pw.dist)[which(grepl(paste("AT",good.alleles[g],sep=""),colnames(pw.dist))==TRUE)]
      getdist<-as.numeric(dist_subset(pw.dist,c(gquery,at.query)))
      print(gquery)
      print(getdist)
      if (length(getdist)>0 && getdist<mindist){
        mindist<-getdist
        minname<-gquery
        ming<-good.alleles[g]
      }
    }
    splitat.best<-substr(ming,regexpr("[^0]",ming),nchar(ming))
    closest.allele<-append(closest.allele,splitat.best)
  }}
closest.allele

AT_import$NewClosestAT <- closest.allele

AT_import <- AT_import %>% 
  rename(
    OriginalAT = V1,
    PreviousAT = V2)

write.csv(AT_import,"ColdgrowATFreq_CrossSect_NGATs.csv")

```





